# Generated by Django 3.2.4 on 2021-06-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interfone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('', ''), ('komp', 'KOMP'), ('utech', 'UTECH')], max_length=25, verbose_name='Modelo')),
                ('ip', models.CharField(max_length=50, verbose_name='IP')),
                ('porta', models.CharField(max_length=6, verbose_name='Porta')),
                ('login', models.CharField(max_length=25, verbose_name='Login')),
                ('senha', models.CharField(max_length=25, verbose_name='Senha')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
    ]
