# Generated by Django 3.2.4 on 2021-06-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violacao',
            name='bi',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='violacao',
            name='cliente',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cliente'),
        ),
    ]
