# Generated by Django 3.2.4 on 2021-06-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistros', '0002_auto_20210611_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violacao',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário Fim'),
        ),
        migrations.AlterField(
            model_name='violacao',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário Início'),
        ),
    ]
